// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-oNRriNf93ZD4x7-dVsiwfBmECl5u35I',
    appId: '1:1078226736187:web:d4480be5bb1040fc78b81e',
    messagingSenderId: '1078226736187',
    projectId: 'ecocig',
    authDomain: 'ecocig.firebaseapp.com',
    storageBucket: 'ecocig.firebasestorage.app',
    measurementId: 'G-BRN8180Q6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDN354kTvPbHSRo3iAGBPUCUWQxpYvhP8',
    appId: '1:1078226736187:android:09819eea9c68afac78b81e',
    messagingSenderId: '1078226736187',
    projectId: 'ecocig',
    storageBucket: 'ecocig.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOL1OQgb0HkROwNsncUV59tKc2a9bcOFc',
    appId: '1:1078226736187:ios:4d1a033fb97aad7678b81e',
    messagingSenderId: '1078226736187',
    projectId: 'ecocig',
    storageBucket: 'ecocig.firebasestorage.app',
    iosBundleId: 'com.example.ecocig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOL1OQgb0HkROwNsncUV59tKc2a9bcOFc',
    appId: '1:1078226736187:ios:4d1a033fb97aad7678b81e',
    messagingSenderId: '1078226736187',
    projectId: 'ecocig',
    storageBucket: 'ecocig.firebasestorage.app',
    iosBundleId: 'com.example.ecocig',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-oNRriNf93ZD4x7-dVsiwfBmECl5u35I',
    appId: '1:1078226736187:web:df8419540ac2e58578b81e',
    messagingSenderId: '1078226736187',
    projectId: 'ecocig',
    authDomain: 'ecocig.firebaseapp.com',
    storageBucket: 'ecocig.firebasestorage.app',
    measurementId: 'G-DEVT5FLJBS',
  );

}